version: '3.13'
services:
  app:
    build: .
    volumes:
      - .:/statutscan-project
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - 8000:8000
    env_file:
      - .env
    image: statutscan-project:django
    container_name: statutscan_project_django_container
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  static_volume:
  media_volume: