version: '3.12'
services:
  app:
    build: .
    volumes:
      - .:/statutscan-project
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - 8000:8000
    env_file:
      - .env
    image: statutscan-project:django
    container_name: statutscan_project_container
    depends_on:
      - mongo
    command: /bin/bash /statutscan-project/build.sh

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/mongo_db
    command: mongod --quiet --logpath /dev/null

volumes:
  static_volume:
  media_volume:
  mongo-data:
