FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1 \
    DJANGO_SETTINGS_MODULE=statutscan_project.settings.local

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
         gcc libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade pip \
    && pip install -r requirements.txt
