# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Django + Next.js to Azure Web App

on:
  push:
    branches:
      - production_setup
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      # 1) Build frontend
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies and build Next.js app
        run: |
          cd frontend
          npm install
          npm run build

      # 2) Prepare Python env
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start python virtual environment
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
      
      - name: Install python dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 3) Zip everything
      - name: Zip artifact for deployment
        run: |
          chmod +x startup.sh
          zip -r release.zip .

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-next-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-next-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d .
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_19F418D23CC445728519C9F4B7B52AE0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C58539E7844A44B2BB09A0B955DDE2D5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_39A5626256114BF78D30317AA630AF77 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'statutscan-backend'
          slot-name: 'Production'
